// corelx_import converts a PNG into a CoreLX bitmap matrix-plane asset, emitted
// as a text block for inclusion in a .corelx source. This is the import-time
// half of the image pathway: binary art becomes deterministic text, and the
// compiler only ever parses text.
//
// Usage: corelx_import <image.png> <AssetName> <planeSize:32|64|128> <paletteBank> [out.corelxasset]
package main

import (
	"fmt"
	"image"
	_ "image/png"
	"os"
	"strconv"
	"strings"

	"nitro-core-dx/internal/emulator"
	ppucore "nitro-core-dx/internal/ppu"
)

func main() {
	if len(os.Args) < 5 {
		fmt.Fprintln(os.Stderr, "Usage: corelx_import <image.png> <AssetName> <planeSize:32|64|128> <paletteBank> [out]")
		os.Exit(1)
	}
	imgPath, name := os.Args[1], os.Args[2]
	planeSize, _ := strconv.Atoi(os.Args[3])
	palBank, _ := strconv.Atoi(os.Args[4])

	var sizeMode uint8
	switch planeSize {
	case 32:
		sizeMode = ppucore.TilemapSize32x32
	case 64:
		sizeMode = ppucore.TilemapSize64x64
	case 128:
		sizeMode = ppucore.TilemapSize128x128
	default:
		fmt.Fprintln(os.Stderr, "planeSize must be 32, 64, or 128")
		os.Exit(1)
	}

	f, err := os.Open(imgPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open %s: %v\n", imgPath, err)
		os.Exit(1)
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		fmt.Fprintf(os.Stderr, "decode %s: %v\n", imgPath, err)
		os.Exit(1)
	}

	asset, err := emulator.BuildBitmapMatrixPlaneAssetFromImage(img, 0, sizeMode, uint8(palBank))
	if err != nil {
		fmt.Fprintf(os.Stderr, "convert: %v\n", err)
		os.Exit(1)
	}
	bitmap := asset.Program.Bitmap
	palette := asset.Palette

	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by corelx_import from %s (%s, plane %d, palette bank %d)\n",
		imgPath, "do not hand-edit the data block", planeSize, palBank)
	fmt.Fprintf(&b, "image %s:\n", name)
	fmt.Fprintf(&b, "    kind: bitmap_plane\n")
	fmt.Fprintf(&b, "    plane_size: %d\n", planeSize)
	fmt.Fprintf(&b, "    palette_bank: %d\n", palBank)
	b.WriteString("    palette: hex")
	for _, c := range palette {
		fmt.Fprintf(&b, " %04x", c)
	}
	b.WriteString("\n    data: hex\n")
	for i := 0; i < len(bitmap); i += 32 {
		end := i + 32
		if end > len(bitmap) {
			end = len(bitmap)
		}
		b.WriteString("        ")
		for j := i; j < end; j++ {
			fmt.Fprintf(&b, "%02x ", bitmap[j])
		}
		b.WriteString("\n")
	}

	out := b.String()
	if len(os.Args) >= 6 {
		if err := os.WriteFile(os.Args[5], []byte(out), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Wrote %s: %d palette entries, %d bitmap bytes (%d text bytes)\n",
			os.Args[5], len(palette), len(bitmap), len(out))
	} else {
		fmt.Print(out)
		fmt.Fprintf(os.Stderr, "[%d palette entries, %d bitmap bytes]\n", len(palette), len(bitmap))
	}
}
